C=====================================================================
C     modern/regress/regval.f
C---------------------------------------------------------------------
C     REGRESSION ORCHESTRATOR / GOLDEN-MASTER COMPARISON DRIVER.
C     PROGRAM REGVAL -- the standalone MAIN (built into regress.exe by
C     test/regress/run_all.csh) that proves the modern/ abstraction
C     layer preserves exact APR.95 solver behavior (AAP 0.2.1, 0.3.1,
C     0.6.3, 0.7.1).
C=====================================================================
C
C     ROLE IN THE REGRESSION HARNESS
C         test/regress/run_all.csh sweeps every benchmark deck
C         inp/<base>.inp through nastrn.exe, producing a candidate OFP
C         output, then invokes THIS program once per deck:
C
C             regress.exe  <candidate.out>  <golden.out>
C
C         REGVAL opens both files READ-ONLY, calls the comparator
C         OUTCOMP (modern/regress/outcomp.f) to compare them field by
C         field, prints a one-line PASS:/FAIL: verdict, and sets the OS
C         process exit status that the harness keys on.  Together,
C         run_all.csh + REGVAL + OUTCOMP form the "regression
C         orchestrator" of AAP 0.2.1.
C
C     LOCKED CONSUMER CONTRACT (from test/regress/run_all.csh)
C         Build : f77 -fast -dn -o regress.exe regval.f outcomp.f
C                 (plus nastlib.a).  regval.f is listed FIRST and
C                 supplies the MAIN program unit; outcomp.f supplies
C                 SUBROUTINE OUTCOMP.  There is no third source file.
C         Invoke: regress.exe $out $ref   (inside foreach deck ...)
C                 ARGUMENT 1 = $out = the CANDIDATE output (freshly
C                                     generated by nastrn.exe).
C                 ARGUMENT 2 = $ref = the GOLDEN master
C                                     (demoout/<base>.out).
C                 The order is CANDIDATE then GOLDEN -- honored here.
C         Signal: the harness reads the PROCESS EXIT STATUS as the
C                 PRIMARY pass/fail signal (0 => PASS, non-zero =>
C                 FAIL) and ALSO captures this program's stdout into
C                 its run log via csh ">>&", then greps it for the
C                 token "FAIL:".
C
C     OUTPUT CHANNEL = STDOUT = FORTRAN LOGICAL UNIT 6  (DECIDED)
C         All output -- usage, the PASS:/FAIL: verdict, and any human-
C         readable difference report from OUTCOMP -- is written to
C         unit 6 (stdout), because run_all.csh redirects THIS program's
C         stdout into its run log.  The harness does NOT map a Fortran
C         unit-3 file for regress.exe; the unit-3 / LOGNM mapping it
C         sets applies ONLY to the solver run (so as not to perturb the
C         OFP).  Writing the verdict to unit 3 here would create a
C         stray fort.3 the harness never sees.  The AAP "diagnostics to
C         unit 3 only / never stdout" rule governs the IN-SOLVER
C         modern/diag/* layer (which must not corrupt the OFP DURING a
C         solver run); REGVAL is a SEPARATE post-run executable whose
C         stdout IS the intended, harness-captured report channel.
C
C     PROGRAM vs SUBROUTINE  (RESOLVED)
C         An earlier modern/ folder note said "routines must be
C         SUBROUTINE/FUNCTION, not PROGRAMs."  That is superseded FOR
C         THIS FILE ONLY by the run_all.csh contract above: regval.f
C         MUST be PROGRAM REGVAL (the MAIN of regress.exe).  The
C         companion outcomp.f remains a pure, reusable SUBROUTINE,
C         which satisfies the deeper "linkable/reusable" intent (both
C         the test/* drivers and regress.exe link OUTCOMP).
C
C     LINKING NOTE  (coordination only -- no build action taken here)
C         Because this file provides a MAIN program unit, the bin/
C         agent must NOT name regval.o (or outcomp.o) explicitly on the
C         nastrn.exe link line (only the 39 bd/ BLOCK DATA objects are
C         named there).  If regval.o is archived into nastlib.a, the
C         linker will not pull it into nastrn.exe because nastrn.o
C         already satisfies MAIN.  bin/linknas is owned by the bin/
C         agent; this comment is informational only.
C
C     SELF-CONTAINED -- NO COMMON, NO EQUIVALENCE, NO INCLUDE.  This
C         driver INCLUDEs none of the nine *.COM headers and declares
C         no COMMON and no EQUIVALENCE; it communicates only through
C         the OUTCOMP argument list and compiler intrinsics.
C         Verifiable by inspection (AAP 0.5.3).
C
C     READS BOTH FILES READ-ONLY (STATUS='OLD'; content is only READ,
C         by OUTCOMP); it never modifies inp/ or demoout/.  REGVAL owns
C         OPEN/CLOSE of the two units; OUTCOMP never opens/closes them.
C
C     NO GUARD CLAUSE.  REGVAL is explicitly-invoked standalone
C         infrastructure that must run unconditionally; it does NOT
C         take IDIAG and is NOT gated by IF (IDIAG .EQ. 0) RETURN.  The
C         modern/ guard-clause rule applies only to IDIAG-gated
C         diagnostic routines, which this is not.
C
C     STRICT FORTRAN 77.  Every name is EXPLICITLY typed below; no
C         IMPLICIT NONE (an F90 feature) is used and no name relies on
C         implicit typing -- matching the sibling outcomp.f and the AAP
C         0.7.2 "no non-F77 dialect features" mandate.  Fixed-form
C         (comment C in col 1; labels in cols 1-5; continuation in
C         col 6; body in cols 7-72).  Compiled by Sun f77 -fast -dn
C         into bin/nastlib.a; also gfortran-clean.
C
C     EXIT-STATUS CONTRACT (the PRIMARY harness signal)
C         0  clean match : IRET = 0 AND NDIFF = 0   -> "PASS: <cand>"
C         1  comparison failure (NDIFF > 0), an I/O or format error
C            (IRET .NE. 0, e.g. the embedded-binary golden master
C            demoout/t01231a.out), or a file-open failure
C                                                   -> "FAIL: <cand>"
C         2  usage error (fewer than two arguments).  A usage error is
C            NOT a deck failure, so it does NOT print the "FAIL:" token.
C
C     PROGRAM UNIT IN THIS FILE
C         REGVAL -- this MAIN driver.  The comparator OUTCOMP lives in
C                   the companion modern/regress/outcomp.f.
C=====================================================================
      PROGRAM REGVAL
C
C     --- local scalars (all explicitly typed; no IMPLICIT NONE) ---
      INTEGER          NARG, NDIFF, IRET, IOS, LENT
C     --- IARGC: Sun f77 / gfortran command-line-count intrinsic ---
      INTEGER          IARGC
C     --- the two file paths supplied on the command line ---
      CHARACTER*256    FTEST, FREF
C     --- logical units: candidate, golden, log (= stdout = unit 6) ---
      INTEGER          LUTST, LUREF, LULOG
      PARAMETER       (LUTST = 11, LUREF = 12, LULOG = 6)
C
C=====================================================================
C     PHASE B -- ACQUIRE THE TWO COMMAND-LINE ARGUMENTS.
C=====================================================================
      NARG = IARGC ()
      IF (NARG .LT. 2) THEN
C        --- usage error: report and exit 2 (NOT a deck FAIL:) ---
         WRITE (LULOG, 9000)
         CALL EXIT (2)
      END IF
      CALL GETARG (1, FTEST)
      CALL GETARG (2, FREF)
C
C     --- trim trailing blanks of the candidate path so the verdict
C     --- line is readable; LENT = last non-blank column (floor 1).
C     --- Nested IF (not a single .AND.) because FORTRAN 77 does not
C     --- short-circuit .AND.; this avoids referencing FTEST(0:0).
      LENT = 256
  100 CONTINUE
      IF (LENT .GT. 1) THEN
         IF (FTEST(LENT:LENT) .EQ. ' ') THEN
            LENT = LENT - 1
            GO TO 100
         END IF
      END IF
C
C=====================================================================
C     PHASE C -- OPEN BOTH STREAMS READ-ONLY (STATUS='OLD').
C     A failure to open EITHER file is a deck FAILURE: emit "FAIL:"
C     keyed on the CANDIDATE path (the harness identifies decks by it)
C     and exit 1.
C=====================================================================
      OPEN (UNIT=LUTST, FILE=FTEST, STATUS='OLD', FORM='FORMATTED',
     &      IOSTAT=IOS)
      IF (IOS .NE. 0) THEN
         WRITE (LULOG, 9100) FTEST(1:LENT)
         CALL EXIT (1)
      END IF
      OPEN (UNIT=LUREF, FILE=FREF, STATUS='OLD', FORM='FORMATTED',
     &      IOSTAT=IOS)
      IF (IOS .NE. 0) THEN
C        --- candidate opened OK; close it before golden exit ---
         CLOSE (LUTST)
         WRITE (LULOG, 9110) FTEST(1:LENT)
         CALL EXIT (1)
      END IF
C
C=====================================================================
C     PHASE D -- FIELD-BY-FIELD COMPARISON VIA OUTCOMP.
C     OUTCOMP reads both already-open streams, writes any per-field
C     difference detail to LULOG (= 6), and returns NDIFF (difference
C     count) and IRET (0 normal / 1 I/O or format error).  It never
C     decides the verdict and never calls EXIT -- that is REGVAL's job.
C=====================================================================
      CALL OUTCOMP (LUTST, LUREF, LULOG, NDIFF, IRET)
      CLOSE (LUTST)
      CLOSE (LUREF)
C
C=====================================================================
C     PHASE E -- VERDICT AND PROCESS EXIT STATUS.
C=====================================================================
      IF (IRET .EQ. 0 .AND. NDIFF .EQ. 0) THEN
C        --- clean match: the ONLY path that exits 0 ---
         WRITE (LULOG, 9200) FTEST(1:LENT)
         CALL EXIT (0)
      ELSE
C        --- any difference or I/O/format error is a FAIL (exit 1) ---
         WRITE (LULOG, 9300) FTEST(1:LENT)
         WRITE (LULOG, 9310) NDIFF
         IF (IRET .NE. 0) WRITE (LULOG, 9320)
         CALL EXIT (1)
      END IF
C
C     --- CALL EXIT never returns; STOP/END are a defensive backstop
C     --- and mirror the canonical bin/nastrn.f PROGRAM termination.
      STOP
C
C=====================================================================
C     OUTPUT FORMATS.  The PASS:/FAIL: verdict lines begin with the
C     literal token in column 1 of the record (NO leading blank) so the
C     harness "grep -c FAIL:" matches and no space precedes the token.
C     The supplementary detail lines are indented and carry no token.
C=====================================================================
 9000 FORMAT ('USAGE: regress.exe <candidate.out> <golden.out>')
 9100 FORMAT ('FAIL: ', A, ' - CANNOT OPEN CANDIDATE FILE')
 9110 FORMAT ('FAIL: ', A, ' - CANNOT OPEN GOLDEN-MASTER FILE')
 9200 FORMAT ('PASS: ', A)
 9300 FORMAT ('FAIL: ', A)
 9310 FORMAT ('       FIELD/LINE DIFFERENCES: ', I8)
 9320 FORMAT ('       I/O OR FORMAT ERROR DURING COMPARISON')
      END
